dist: trusty
sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

jobs:
  include:
    - &test
      name: "Lint & Tests: PHP 7.0, TYPO3v8"
      php: 7.0
      env: TYPO3_VERSION=^8.7
      install:
        - composer require typo3/cms-core="$TYPO3_VERSION"
      script:
        - composer lint:php
        - composer test

    - <<: *test
      name: "Lint & Tests: PHP 7.2, TYPO3v9"
      php: 7.2
      env: TYPO3_VERSION=^9.5

    - <<: *test
      name: "Lint & Tests: PHP 7.1, TYPO3v8"
      php: 7.1

    - php: 7.1
      name: TypoScript lint
      script:
        - composer lint:typoscript

    - php: 7.1
      name: XML lint
      script:
        - composer lint:xml

    - php: 7.1
      name: Codestyle
      script:
        - composer lint:style

    - php: 7.2
      name: Static analysis
      install:
        - composer require --dev phpstan/phpstan:^0.10 saschaegerer/phpstan-typo3
      script:
        - composer analyze:php

    - stage: deploy
      name: "Upload to TER"
      if: tag IS present
      php: 7.0
      before_install: skip
      install: skip
      before_script: skip
      script: |
        echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n"

        TAG_ANNOTATION="$(git tag -n -l $TRAVIS_TAG)"
        TAG_MESSAGE="${TAG_ANNOTATION#* }"
        EXTENSION_KEY="$(composer config extra.typo3/cms.extension-key)"

        export PATH=$PATH:$(composer global config bin-dir --absolute 2>/dev/null)
        git reset --hard
        git clean -xfd

        echo "Creating phar files for vendors"
        composer global require clue/phar-composer
        mkdir -p /tmp/vendors
        pushd /tmp/vendors
        composer require league/csv:^9.1 nimmneun/onesheet:^1.0
        phar-composer build
        popd
        cp /tmp/vendors/vendors.phar .
        echo "require 'phar://' . \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('${EXTENSION_KEY}') . 'vendors.phar/vendor/autoload.php';" >> ext_localconf.php

        composer global require helhum/ter-client

        echo "Uploading release ${TRAVIS_TAG} to TER"
        ter-client upload "$EXTENSION_KEY" . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE"

notifications:
  slack:
    secure: TPgLYBAyIa6V6RT3YqndCnpkiifnY01ehmPrhVHU3G3yC4e4PtnqftgCrg8D4IBbmlVTxncNbsDqNbFfBEaJ1dMv6tv0yMpYlllfN5Syl3nBcjh43rHN4DWEffgJ59dAhJJtWjHvPfYR1/80EdKzsmepQl1i1+CXH1ryxtS6jEU=
