services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Pagemachine\Formlog\:
    resource: '../Classes/*'

  Pagemachine\Formlog\Controller\Backend\FormLogSuggestController:
    public: true
